Blockiverse: bvnet::object Class Reference
bvnet::object Class Reference
ABC for remotable objects.
#include <protocol.hpp>
Public Member Functions
object (session &sess)
construction of an object
virtual ~object ()
base dtor to automatically unregister the object
virtual const char * getType ()
Get object's identity.
Protected Member Functions
void register_dmc (string label, dmc func)
register dmc method
const string methodLabel (const unsigned int idx)
const unsigned int methodSlot (const string &label)
void dmc_GetType (value_queue &)
the GetType dispatched method call (dmc)
Protected Attributes
session & ctx
for objects to attach to the session's registry
Private Member Functions
void methodCall (unsigned int idx)
Private Attributes
call_map dmcTable
method mapper for method call and OO mechanism
name_map dmcLabel
name labels of dmc methods
indx_map dmcIndex
method indices of dmc method
Friends
class session
Displateched Method Call.
Detailed Description
ABC for remotable objects.
Base used for objects exchangeable via object references.
Objects with active references may have methods invoked via the implemented dispatched method call mechanism. This system is OO-friendly and allows runtime polymorphism. Each object instance has its own dmc table (think c++ vtable) which may be be modified at runtime after initial setting by the ctor. One use is to swap out initial (compiled) methods for methods invoking lua scripted forms executed via the (future) embedded lua interpretor. In this form you get the javascript-esque object method redefinition capability. The other purpose is to allow proper OO inheritence in derived classes in the heararchy which may override previous bases' dmc table entries within their ctors.
Since secure referencing requires a way to track object lifetime a registry reference is required for construction.
Definition at line 414 of file protocol.hpp.
Constructor & Destructor Documentation
bvnet::object::object (session & sess) inline
construction of an object
Parameters
sess reference to session to attach
Definition at line 495 of file protocol.hpp.
References dmc_GetType(), LOCK_COUT, bvnet::session::register_object(), and UNLOCK_COUT.
virtual bvnet::object::~object () inline virtual
base dtor to automatically unregister the object
Definition at line 505 of file protocol.hpp.
References LOCK_COUT, UNLOCK_COUT, and bvnet::session::unregister().
Member Function Documentation
void bvnet::object::dmc_GetType (value_queue & vqueue) inline protected
the GetType dispatched method call (dmc)
Definition at line 523 of file protocol.hpp.
Referenced by object().
virtual const char* bvnet::object::getType () inline virtual
Get object's identity.
Returns
Object identity string
Overriden by superclass to announce it's identity.
Reimplemented in serverRoot, Account, and clientRoot.
Definition at line 517 of file protocol.hpp.
Referenced by bvnet::registry::dump(), and bvnet::session::on_recv_call_idx().
void bvnet::object::methodCall (unsigned int idx) inline private
Definition at line 443 of file protocol.hpp.
Referenced by bvnet::session::on_recv_call_idx().
const string bvnet::object::methodLabel (const unsigned int idx) inline protected
Definition at line 476 of file protocol.hpp.
Referenced by bvnet::session::on_recv_call_idx().
const unsigned int bvnet::object::methodSlot (const string & label) inline protected
Definition at line 484 of file protocol.hpp.
void bvnet::object::register_dmc (string label, dmc func) inline protected
register dmc method
Parameters
label method label
func method function
Definition at line 461 of file protocol.hpp.
References bvnet::session::getIdOf(), and bvnet::session::getSendQueue().
Referenced by serverRoot::serverRoot().
Friends And Related Function Documentation
friend class session friend
Displateched Method Call.
Implements dispatched method call (dmc)
Superclass-installed dmc methods in dmcTable are callable by the remote. A superclass sets up his dmc methods in his ctor by accessing object's dmcTable
As a plus the lock and value queue boilerplate has been been moved to the base class dispatcher and the dmc methods will be in locked context and given the value queue as a parameter. He also has an exception now to trap calls to an unimplemented method index.
Todo:
some sort of static enum to get rid of the magic number method call #s from remote POV? I'll have the ctors store method labels in the base class dmcName map while it is setting up the dmc methods.
Todo:
automatically declare the methods for method calling via some sort of macro or metacode?
Definition at line 442 of file protocol.hpp.
Member Data Documentation
session& bvnet::object::ctx protected
for objects to attach to the session's registry
Definition at line 458 of file protocol.hpp.
Referenced by serverRoot::dmc_AnswerChallenge(), serverRoot::dmc_GetAccount(), and serverRoot::dmc_LoginClient().
indx_map bvnet::object::dmcIndex private
method indices of dmc method
Definition at line 456 of file protocol.hpp.
name_map bvnet::object::dmcLabel private
name labels of dmc methods
Definition at line 455 of file protocol.hpp.
call_map bvnet::object::dmcTable private
method mapper for method call and OO mechanism
Definition at line 454 of file protocol.hpp.
The documentation for this class was generated from the following file:
protocol.hpp