Blockiverse: serverRoot Class Reference
serverRoot Class Reference
#include <server.hpp>
Public Member Functions
serverRoot (bvnet::session &sess)
virtual ~serverRoot ()
virtual const char * getType ()
Get object's identity.
Public Member Functions inherited from bvnet::object
object (session &sess)
construction of an object
virtual ~object ()
base dtor to automatically unregister the object
Protected Member Functions
void dmc_LoginClient (value_queue &vqueue)
void dmc_AnswerChallenge (value_queue &vqueue)
void dmc_GetAccount (value_queue &vqueue)
Protected Member Functions inherited from bvnet::object
void register_dmc (string label, dmc func)
register dmc method
const string methodLabel (const unsigned int idx)
const unsigned int methodSlot (const string &label)
void dmc_GetType (value_queue &)
the GetType dispatched method call (dmc)
Private Attributes
BigInt cli_pub_mod
BigInt cli_pub_exp
Key * clientKey
bool clientValid
string challenge
SQLiteDB db
unsigned int randbits [8]
Additional Inherited Members
Protected Attributes inherited from bvnet::object
session & ctx
for objects to attach to the session's registry
Detailed Description
Definition at line 54 of file server.hpp.
Constructor & Destructor Documentation
serverRoot::serverRoot (bvnet::session & sess) inline
Definition at line 68 of file server.hpp.
References dmc_AnswerChallenge(), dmc_GetAccount(), dmc_LoginClient(), and bvnet::object::register_dmc().
virtual serverRoot::~serverRoot () inline virtual
Definition at line 77 of file server.hpp.
References clientKey.
Member Function Documentation
void serverRoot::dmc_AnswerChallenge (value_queue & vqueue) protected
Definition at line 239 of file server.cpp.
References challenge, clientValid, bvnet::object::ctx, bvnet::session::disconnect(), and bvnet::session::getarg().
Referenced by serverRoot().
void serverRoot::dmc_GetAccount (value_queue & vqueue) protected
Definition at line 276 of file server.cpp.
References bvdb::SQLiteDB::bind(), cli_pub_exp, cli_pub_mod, clientKey, clientValid, bvnet::object::ctx, db, bvnet::session::disconnect(), bvdb::SQLiteDB::get_result(), bvnet::session::getarg(), LOCK_COUT, bvdb::SQLiteDB::prepare(), bvdb::SQLiteDB::run(), and UNLOCK_COUT.
Referenced by serverRoot().
void serverRoot::dmc_LoginClient (value_queue & vqueue) protected
Definition at line 204 of file server.cpp.
References challenge, cli_pub_exp, cli_pub_mod, clientKey, bvnet::object::ctx, entropy, bvnet::session::getarg(), and randbits.
Referenced by serverRoot().
virtual const char* serverRoot::getType () inline virtual
Get object's identity.
Returns
Object identity string
Overriden by superclass to announce it's identity.
Reimplemented from bvnet::object.
Definition at line 82 of file server.hpp.
Member Data Documentation
string serverRoot::challenge private
Definition at line 60 of file server.hpp.
Referenced by dmc_AnswerChallenge(), and dmc_LoginClient().
BigInt serverRoot::cli_pub_exp private
Definition at line 57 of file server.hpp.
Referenced by dmc_GetAccount(), and dmc_LoginClient().
BigInt serverRoot::cli_pub_mod private
Definition at line 56 of file server.hpp.
Referenced by dmc_GetAccount(), and dmc_LoginClient().
Key* serverRoot::clientKey private
Definition at line 58 of file server.hpp.
Referenced by dmc_GetAccount(), dmc_LoginClient(), and ~serverRoot().
bool serverRoot::clientValid private
Definition at line 59 of file server.hpp.
Referenced by dmc_AnswerChallenge(), and dmc_GetAccount().
SQLiteDB serverRoot::db private
Definition at line 61 of file server.hpp.
Referenced by dmc_GetAccount().
unsigned int serverRoot::randbits[8] private
Definition at line 62 of file server.hpp.
Referenced by dmc_LoginClient().
The documentation for this class was generated from the following files:
server.hpp
server.cpp