Blockiverse: bvnet::session Class Reference
bvnet::session Class Reference
Symmetrical endpoint session for established connection.
#include <protocol.hpp>
Public Member Functions
session ()
virtual ~session ()
void UpdateInterface (u32, string, u32)
u32 getIdOf (object *ob)
void notify_remove (u32 id)
gets id of specified object
void disconnect ()
close the conncetion
int register_object (object *o)
register object as available to remote
u32 getRemote ()
get remote's root (bootstrap) object
bool hasRemote ()
true indicates remote root object valid
bool unregister (u32 id)
unregister object by-id and inform remote
bool unregister (object *ob)
unregister object by-address and inform remote
void encode (const boost::any &a)
sends any queued values over the wire
valtype argtype ()
Determine type of result stack top value.
int argcount ()
current size of result stack
template<typename V >
V getarg ()
Receive next value from top of return stack.
void bootstrap (object *root)
Handshake/bootstrap process.
void send_int (s64 val)
send int to remote
void send_float (float val)
send float to remote
void send_blob (string val)
send blob (as string) to remote
void send_string (string val)
send string to remote
void send_obref (u32 id)
send object referebce to remote
void send_call (u32 id, u32 m, lpvFunc cb=NULL, int rcount=0)
Remote method call.
void send_call (u32 id, string m_name, lpvFunc cb=NULL, int rcount=0)
bool isValidObject (u32 obid)
Queries if an object still valid and useable on remote.
bool run ()
network pump - blocks until data received.
bool poll ()
network pump - returns to allow other activy whilst waiting.
value_queue & getSendQueue ()
get outgoing value queue for this session
mutex & getMutex ()
get thread lock for this session
void set_conn (tcp::socket &s)
associate connection
void dump (std::ostream &os)
for debugging - dumps data about session
Protected Member Functions
void on_recv (const boost::system::error_code &ec, size_t rlen)
various async data reception callbacks
void on_recv_dead_obid (const boost::system::error_code &ec)
various async data reception callbacks
void on_recv_call_obid (const boost::system::error_code &ec)
various async data reception callbacks
void on_recv_call_idx (const boost::system::error_code &ec, u32 obid)
various async data reception callbacks
void on_recv_oref (const boost::system::error_code &ec, size_t rlen)
various async data reception callbacks
void on_recv_str (const boost::system::error_code &ec, char *buf)
various async data reception callbacks
void on_recv_len (const boost::system::error_code &ec, size_t rlen)
various async data reception callbacks
void on_recv_s64 (const boost::system::error_code &ec, u32 bsize)
various async data reception callbacks
void on_recv_dmc_obid (const boost::system::error_code &ec)
various async data reception callbacks
void on_recv_dmc_len (const boost::system::error_code &ec, dmc_msg mk_dmc)
void on_recv_dmc_label (const boost::system::error_code &ec, dmc_msg mk_dmc, char *buf)
void on_recv_dmc_slot (const boost::system::error_code &ec, dmc_msg mk_dmc)
void on_write_done (string *finsihedbuf)
various async trasnfer completion callbacks
void on_write_call_done (string *finishedbuf, lpvFunc cb)
various async trasnfer completion callbacks
void check_argnotify ()
notifies callback when expected number of return arguments arrive
Protected Attributes
value_stack argstack
incoming results stack
value_queue sendq
outgoing values queue
proxy_map proxy
cache of available remote objects
cb_queue argnotify
callbacks to notify when remote methods complete
iface_map contracts
interfaces map of all remote objects
registry * reg
registered objects in session
mutex * synchro
mutex on session manipulation
tcp::socket * conn
connection
u32 remoteRoot
once booted has remote_root
Private Attributes
io_service * io_
io_service for this session
object * root
session's root (bootstrap) object
bool isActive
connection is alive
bool isBooting
session is in handshake/bootstrap phase
bool _float_or_semi
expecting floating point chars or terminating ;
bool _neg_int
got - meaning incoming int is a negative
bool _opcode_read_queued
when true already waiting for opcode to arrive
string _fpstr
accumulator to receive incoming floating point value
char in_ch
the character just received
char in_idx [4]
the uint32 just received
char in_s64 [8]
the sint64 just received
Detailed Description
Symmetrical endpoint session for established connection.
Maintains the state of the session while the endpoint is connected. The protocol is mainly symmetrical – both endpoints have the same communication language. Once a bootstrap/hnadshake announces the root object the session will asynchronously wait for incoming data with the possibility of sending data or method calls upstream to the remote (and symmetrically processing any such data or method calls received from the remote).
Definition at line 189 of file protocol.hpp.
Constructor & Destructor Documentation
bvnet::session::session () inline
Definition at line 716 of file protocol.hpp.
bvnet::session::~session () inline virtual
Definition at line 726 of file protocol.hpp.
Member Function Documentation
int bvnet::session::argcount () inline
current size of result stack
Definition at line 268 of file protocol.hpp.
Referenced by main().
valtype bvnet::session::argtype () inline
Determine type of result stack top value.
Exceptions
argstack_empty if the result stack is empty when attempted
Definition at line 261 of file protocol.hpp.
Referenced by main().
void bvnet::session::bootstrap (object * root) inline
Handshake/bootstrap process.
Definition at line 754 of file protocol.hpp.
Referenced by main(), and server_boot().
void bvnet::session::check_argnotify () inline protected
notifies callback when expected number of return arguments arrive
Notifies stored callback when argstack reaches specified size
Definition at line 1129 of file protocol.hpp.
References bvnet::method_call::callbk.
void bvnet::session::disconnect () inline
close the conncetion
Definition at line 250 of file protocol.hpp.
Referenced by serverRoot::dmc_AnswerChallenge(), and serverRoot::dmc_GetAccount().
void bvnet::session::dump (std::ostream & os) inline
for debugging - dumps data about session
Definition at line 1308 of file protocol.hpp.
References LOCK_COUT, and UNLOCK_COUT.
void bvnet::session::encode (const boost::any & a) inline
sends any queued values over the wire
Definition at line 1202 of file protocol.hpp.
References bvnet::method_call::callbk, bvnet::method_call::id, bvnet::method_call::idx, bvnet::dmc_msg::label, LOCK_COUT, log2_tbl, bvnet::dmc_msg::ob, on_write_done(), pow2_tbl, bvnet::method_call::rcount, bvnet::dmc_msg::slot, UNLOCK_COUT, bvnet::vtBlob, bvnet::vtDeath, bvnet::vtDMC, bvnet::vtFloat, bvnet::vtInt, bvnet::vtMethod, bvnet::vtObref, and bvnet::vtString.
template<typename V > V bvnet::session::getarg () inline
Receive next value from top of return stack.
Since the value stack holds arbitrary types getarg is templated in order to provide a different return value type for all value types possible to be received.
Exceptions
argstack_empty if the result stack is empty when attempted
Definition at line 279 of file protocol.hpp.
Referenced by serverRoot::dmc_AnswerChallenge(), serverRoot::dmc_GetAccount(), serverRoot::dmc_LoginClient(), loginDone(), main(), onGetAccount(), testLogin(), and testNotify().
u32 bvnet::session::getIdOf (object * ob) inline
Definition at line 738 of file protocol.hpp.
Referenced by bvnet::object::register_dmc().
mutex& bvnet::session::getMutex () inline
get thread lock for this session
Definition at line 333 of file protocol.hpp.
u32 bvnet::session::getRemote () inline
get remote's root (bootstrap) object
Definition at line 252 of file protocol.hpp.
Referenced by main().
value_queue& bvnet::session::getSendQueue () inline
get outgoing value queue for this session
Definition at line 331 of file protocol.hpp.
Referenced by bvnet::object::register_dmc().
bool bvnet::session::hasRemote () inline
true indicates remote root object valid
Definition at line 253 of file protocol.hpp.
Referenced by main().
bool bvnet::session::isValidObject (u32 obid) inline
Queries if an object still valid and useable on remote.
Parameters
obid object id.
Returns
true if oject useable false otherwise.
Definition at line 323 of file protocol.hpp.
void bvnet::session::notify_remove (u32 id) inline
gets id of specified object
signals that object no longer valid
Definition at line 741 of file protocol.hpp.
void bvnet::session::on_recv (const boost::system::error_code & ec, size_t rlen) inline protected
various async data reception callbacks
Definition at line 1012 of file protocol.hpp.
References LOCK_COUT, on_recv_call_obid(), on_recv_dead_obid(), on_recv_dmc_obid(), on_recv_len(), on_recv_oref(), on_recv_s64(), pow2_tbl, and UNLOCK_COUT.
Referenced by poll(), and run().
void bvnet::session::on_recv_call_idx (const boost::system::error_code & ec, u32 obid) inline protected
various async data reception callbacks
Definition at line 970 of file protocol.hpp.
References bvnet::object::getType(), LOCK_COUT, bvnet::object::methodCall(), bvnet::object::methodLabel(), and UNLOCK_COUT.
Referenced by on_recv_call_obid().
void bvnet::session::on_recv_call_obid (const boost::system::error_code & ec) inline protected
various async data reception callbacks
Definition at line 859 of file protocol.hpp.
References LOCK_COUT, on_recv_call_idx(), and UNLOCK_COUT.
Referenced by on_recv().
void bvnet::session::on_recv_dead_obid (const boost::system::error_code & ec) inline protected
various async data reception callbacks
Definition at line 835 of file protocol.hpp.
References LOCK_COUT, and UNLOCK_COUT.
Referenced by on_recv().
void bvnet::session::on_recv_dmc_label (const boost::system::error_code & ec, dmc_msg mk_dmc, char * buf) inline protected
Definition at line 926 of file protocol.hpp.
References bvnet::registry_full::buf, bvnet::dmc_msg::label, LOCK_COUT, on_recv_dmc_slot(), and UNLOCK_COUT.
Referenced by on_recv_dmc_len().
void bvnet::session::on_recv_dmc_len (const boost::system::error_code & ec, dmc_msg mk_dmc) inline protected
Definition at line 902 of file protocol.hpp.
References LOCK_COUT, on_recv_dmc_label(), and UNLOCK_COUT.
Referenced by on_recv_dmc_obid().
void bvnet::session::on_recv_dmc_obid (const boost::system::error_code & ec) inline protected
various async data reception callbacks
Definition at line 880 of file protocol.hpp.
References LOCK_COUT, bvnet::dmc_msg::ob, on_recv_dmc_len(), and UNLOCK_COUT.
Referenced by on_recv().
void bvnet::session::on_recv_dmc_slot (const boost::system::error_code & ec, dmc_msg mk_dmc) inline protected
Definition at line 949 of file protocol.hpp.
References bvnet::dmc_msg::label, LOCK_COUT, bvnet::dmc_msg::ob, bvnet::dmc_msg::slot, and UNLOCK_COUT.
Referenced by on_recv_dmc_label().
void bvnet::session::on_recv_len (const boost::system::error_code & ec, size_t rlen) inline protected
various async data reception callbacks
Definition at line 811 of file protocol.hpp.
References LOCK_COUT, on_recv_str(), and UNLOCK_COUT.
Referenced by on_recv().
void bvnet::session::on_recv_oref (const boost::system::error_code & ec, size_t rlen) inline protected
various async data reception callbacks
Definition at line 767 of file protocol.hpp.
References LOCK_COUT, and UNLOCK_COUT.
Referenced by on_recv().
void bvnet::session::on_recv_s64 (const boost::system::error_code & ec, u32 bsize) inline protected
various async data reception callbacks
Definition at line 992 of file protocol.hpp.
References LOCK_COUT, and UNLOCK_COUT.
Referenced by on_recv().
void bvnet::session::on_recv_str (const boost::system::error_code & ec, char * buf) inline protected
various async data reception callbacks
Definition at line 796 of file protocol.hpp.
References bvnet::registry_full::buf, LOCK_COUT, and UNLOCK_COUT.
Referenced by on_recv_len().
void bvnet::session::on_write_call_done (string * finishedbuf, lpvFunc cb) inline protected
various async trasnfer completion callbacks
Definition at line 763 of file protocol.hpp.
void bvnet::session::on_write_done (string * finsihedbuf) inline protected
various async trasnfer completion callbacks
Definition at line 760 of file protocol.hpp.
Referenced by encode().
bool bvnet::session::poll () inline
network pump - returns to allow other activy whilst waiting.
Definition at line 1172 of file protocol.hpp.
References LOCK_COUT, on_recv(), and UNLOCK_COUT.
Referenced by main().
int bvnet::session::register_object (object * o) inline
register object as available to remote
Definition at line 745 of file protocol.hpp.
Referenced by bvnet::object::object().
bool bvnet::session::run () inline
network pump - blocks until data received.
Definition at line 1142 of file protocol.hpp.
References LOCK_COUT, on_recv(), and UNLOCK_COUT.
Referenced by main(), and server_boot().
void bvnet::session::send_blob (string val) inline
send blob (as string) to remote
Definition at line 293 of file protocol.hpp.
void bvnet::session::send_call (u32 id, u32 m, lpvFunc cb = NULL, int rcount = 0) inline
Remote method call.
Creates method call message to send to remote.
Parameters
id object id for method
m method number
cb callback invoked when method completed. Default: NULL (no callback).
rcount expected number of returned values. Default: 0 (no values returned).
Definition at line 309 of file protocol.hpp.
Referenced by main(), and testLogin().
void bvnet::session::send_call (u32 id, string m_name, lpvFunc cb = NULL, int rcount = 0) inline
Definition at line 312 of file protocol.hpp.
void bvnet::session::send_float (float val) inline
send float to remote
Definition at line 291 of file protocol.hpp.
void bvnet::session::send_int (s64 val) inline
send int to remote
Definition at line 289 of file protocol.hpp.
void bvnet::session::send_obref (u32 id) inline
send object referebce to remote
Definition at line 297 of file protocol.hpp.
void bvnet::session::send_string (string val) inline
send string to remote
Definition at line 295 of file protocol.hpp.
Referenced by main(), and testLogin().
void bvnet::session::set_conn (tcp::socket & s) inline
associate connection
Parameters
s socket to utilize for session
Definition at line 335 of file protocol.hpp.
References LOCK_COUT, and UNLOCK_COUT.
Referenced by main(), and server_main().
bool bvnet::session::unregister (u32 id) inline
unregister object by-id and inform remote
Definition at line 748 of file protocol.hpp.
Referenced by bvnet::object::~object().
bool bvnet::session::unregister (object * ob) inline
unregister object by-address and inform remote
Definition at line 751 of file protocol.hpp.
void bvnet::session::UpdateInterface (u32 ob, string label, u32 slot) inline
Definition at line 730 of file protocol.hpp.
References LOCK_COUT, and UNLOCK_COUT.
Member Data Documentation
bool bvnet::session::_float_or_semi private
expecting floating point chars or terminating ;
Definition at line 195 of file protocol.hpp.
string bvnet::session::_fpstr private
accumulator to receive incoming floating point value
Definition at line 198 of file protocol.hpp.
bool bvnet::session::_neg_int private
got - meaning incoming int is a negative
Definition at line 196 of file protocol.hpp.
bool bvnet::session::_opcode_read_queued private
when true already waiting for opcode to arrive
Definition at line 197 of file protocol.hpp.
cb_queue bvnet::session::argnotify protected
callbacks to notify when remote methods complete
Definition at line 234 of file protocol.hpp.
value_stack bvnet::session::argstack protected
incoming results stack
Definition at line 231 of file protocol.hpp.
tcp::socket* bvnet::session::conn protected
connection
Definition at line 239 of file protocol.hpp.
iface_map bvnet::session::contracts protected
interfaces map of all remote objects
Definition at line 235 of file protocol.hpp.
char bvnet::session::in_ch private
the character just received
Definition at line 199 of file protocol.hpp.
char bvnet::session::in_idx[4] private
the uint32 just received
Definition at line 200 of file protocol.hpp.
char bvnet::session::in_s64[8] private
the sint64 just received
Definition at line 201 of file protocol.hpp.
io_service* bvnet::session::io_ private
io_service for this session
Definition at line 191 of file protocol.hpp.
bool bvnet::session::isActive private
connection is alive
Definition at line 193 of file protocol.hpp.
bool bvnet::session::isBooting private
session is in handshake/bootstrap phase
Definition at line 194 of file protocol.hpp.
proxy_map bvnet::session::proxy protected
cache of available remote objects
Definition at line 233 of file protocol.hpp.
registry* bvnet::session::reg protected
registered objects in session
Definition at line 237 of file protocol.hpp.
u32 bvnet::session::remoteRoot protected
once booted has remote_root
Definition at line 241 of file protocol.hpp.
object* bvnet::session::root private
session's root (bootstrap) object
Definition at line 192 of file protocol.hpp.
value_queue bvnet::session::sendq protected
outgoing values queue
Definition at line 232 of file protocol.hpp.
mutex* bvnet::session::synchro protected
mutex on session manipulation
Definition at line 238 of file protocol.hpp.
The documentation for this class was generated from the following file:
protocol.hpp