Blockiverse: bvdb::SQLiteDB Class Reference
bvdb::SQLiteDB Class Reference
Manager class for SQLite3 database and connections.
#include <database.hpp>
Public Types
typedef std::shared_ptr< Result > query_result
typedef sqlite3_stmt * statement
Public Member Functions
SQLiteDB ()
virtual ~SQLiteDB ()
template<typename T >
T get_result (query_result rslt, int row, int col)
query_result run (sqlite3_stmt *stmt)
void bind (statement s, int idx, const string &val)
void bind (statement s, int idx, const char *val, int len)
void bind (statement s, int idx, s64 &val)
void bind (statement s, int idx, int &val)
void bind (statement s, int idx, double &val)
void bind_null (statement s, int idx)
sqlite3_stmt * prepare (string sql)
void runOnce (const string sql)
Static Public Member Functions
static void init (const string path)
Private Attributes
sqlite3 * db
stmt_map stmtCache
optimizer cache of statements for faster operations These will be appropriately released in dtor
Static Private Attributes
static string file
Detailed Description
Manager class for SQLite3 database and connections.
Manages specification of database file, creating connections and shutting down.
Cacheing system utilizes prepared statements to remember SQL statements on first use to prevent the overhead of subsequent compilations of SQL statements so long as class user utilizes binding semantics versus inline parameters.
Definition at line 167 of file database.hpp.
Member Typedef Documentation
typedef std::shared_ptr<Result> bvdb::SQLiteDB::query_result
Definition at line 205 of file database.hpp.
typedef sqlite3_stmt* bvdb::SQLiteDB::statement
Definition at line 257 of file database.hpp.
Constructor & Destructor Documentation
bvdb::SQLiteDB::SQLiteDB () inline
Definition at line 181 of file database.hpp.
References bvdb::DBError::busy_aware_throw(), and db.
virtual bvdb::SQLiteDB::~SQLiteDB () inline virtual
Definition at line 191 of file database.hpp.
References LOCK_COUT, and UNLOCK_COUT.
Member Function Documentation
void bvdb::SQLiteDB::bind (statement s, int idx, const string & val) inline
bind argument with a string
Definition at line 258 of file database.hpp.
References bvdb::DBError::busy_aware_throw(), LOCK_COUT, and UNLOCK_COUT.
Referenced by serverRoot::dmc_GetAccount().
void bvdb::SQLiteDB::bind (statement s, int idx, const char * val, int len) inline
bind argument with binary data (blob)
Definition at line 268 of file database.hpp.
References bvdb::DBError::busy_aware_throw(), LOCK_COUT, and UNLOCK_COUT.
void bvdb::SQLiteDB::bind (statement s, int idx, s64 & val) inline
bind argument with an int64
Definition at line 278 of file database.hpp.
References bvdb::DBError::busy_aware_throw(), LOCK_COUT, and UNLOCK_COUT.
void bvdb::SQLiteDB::bind (statement s, int idx, int & val) inline
bind argument with an integer
Definition at line 288 of file database.hpp.
References bvdb::DBError::busy_aware_throw(), LOCK_COUT, and UNLOCK_COUT.
void bvdb::SQLiteDB::bind (statement s, int idx, double & val) inline
bind argument with a double
Definition at line 298 of file database.hpp.
References bvdb::DBError::busy_aware_throw(), LOCK_COUT, and UNLOCK_COUT.
void bvdb::SQLiteDB::bind_null (statement s, int idx) inline
bind argument with nothing (null)
Definition at line 308 of file database.hpp.
References bvdb::DBError::busy_aware_throw(), LOCK_COUT, and UNLOCK_COUT.
template<typename T > T bvdb::SQLiteDB::get_result (query_result rslt, int row, int col) inline
Definition at line 207 of file database.hpp.
Referenced by serverRoot::dmc_GetAccount().
static void bvdb::SQLiteDB::init (const string path) inline static
Definition at line 175 of file database.hpp.
Referenced by bvdb::init_db().
sqlite3_stmt* bvdb::SQLiteDB::prepare (string sql) inline
compile sql to prepared statement Results will be cached so compiles aren't repeated. Statement will be reset on cache hit.
Definition at line 318 of file database.hpp.
References bvdb::DBError::busy_aware_throw(), LOCK_COUT, and UNLOCK_COUT.
Referenced by serverRoot::dmc_GetAccount().
query_result bvdb::SQLiteDB::run (sqlite3_stmt * stmt) inline
Definition at line 209 of file database.hpp.
References bvdb::DBError::busy_aware_throw(), LOCK_COUT, and UNLOCK_COUT.
Referenced by serverRoot::dmc_GetAccount().
void bvdb::SQLiteDB::runOnce (const string sql) inline
Run SQL commend once
Runs an SQL intneded to be used only once (eg: table initializer) thus no cacheing is performed of the SQL statement (ie: prepared statements).
Furthermore assumes no results.
Parameters
sql SQL statement to execute
Exceptions
DBError should execution fail
Definition at line 355 of file database.hpp.
References bvdb::DBError::busy_aware_throw(), LOCK_COUT, bvdb::DBError::release, and UNLOCK_COUT.
Referenced by server_main().
Member Data Documentation
sqlite3* bvdb::SQLiteDB::db private
Definition at line 170 of file database.hpp.
Referenced by SQLiteDB().
string bvdb::SQLiteDB::file static private
Definition at line 169 of file database.hpp.
stmt_map bvdb::SQLiteDB::stmtCache private
optimizer cache of statements for faster operations These will be appropriately released in dtor
Definition at line 173 of file database.hpp.
The documentation for this class was generated from the following files:
database.hpp
database.cpp