Blockiverse: Configurator Class Reference
Configurator Class Reference
#include <settings.hpp>
Public Types
typedef property_map::iterator iterator
Public Member Functions
Configurator (const string &, defaultor=NULL)
~Configurator ()
void read_cmdline (int, char **)
iterator begin ()
iterator end ()
cfg_val & operator[] (const cfg_key &id)
Protected Member Functions
virtual void process_clause (const string &, const string &)
Private Types
typedef property_map::key_type cfg_key
typedef property_map::mapped_type cfg_val
typedef void(* defaultor)(Configurator &)
Private Member Functions
void read ()
void write ()
void process_line (const string &)
Private Attributes
property_map cfg
string cfgFile
Detailed Description
Definition at line 31 of file settings.hpp.
Member Typedef Documentation
typedef property_map::key_type Configurator::cfg_key private
Definition at line 33 of file settings.hpp.
typedef property_map::mapped_type Configurator::cfg_val private
Definition at line 34 of file settings.hpp.
typedef void(* Configurator::defaultor)(Configurator &) private
Definition at line 40 of file settings.hpp.
typedef property_map::iterator Configurator::iterator
Definition at line 49 of file settings.hpp.
Constructor & Destructor Documentation
Configurator::Configurator (const string & , defaultor = NULL)
Definition at line 31 of file settings.cpp.
References cfgFile, and read().
Configurator::~Configurator () inline
Definition at line 45 of file settings.hpp.
References write().
Member Function Documentation
iterator Configurator::begin () inline
Definition at line 50 of file settings.hpp.
iterator Configurator::end () inline
Definition at line 51 of file settings.hpp.
cfg_val& Configurator::operator[] (const cfg_key & id) inline
Definition at line 52 of file settings.hpp.
void Configurator::process_clause (const string & , const string &) protected virtual
Definition at line 47 of file settings.cpp.
References cfg, cfgFile, LOCK_COUT, and UNLOCK_COUT.
Referenced by process_line().
void Configurator::process_line (const string &) private
Definition at line 39 of file settings.cpp.
References process_clause().
Referenced by read(), and read_cmdline().
void Configurator::read () private
Definition at line 64 of file settings.cpp.
References cfgFile, and process_line().
Referenced by Configurator().
void Configurator::read_cmdline (int argc, char ** argv)
Definition at line 55 of file settings.cpp.
References process_line().
Referenced by main(), and server_main().
void Configurator::write () private
Definition at line 77 of file settings.cpp.
References cfg, and cfgFile.
Referenced by ~Configurator().
Member Data Documentation
property_map Configurator::cfg private
Definition at line 35 of file settings.hpp.
Referenced by process_clause(), and write().
string Configurator::cfgFile private
Definition at line 36 of file settings.hpp.
Referenced by Configurator(), process_clause(), read(), and write().
The documentation for this class was generated from the following files:
settings.hpp
settings.cpp