Blockiverse: main.cpp File Reference
main.cpp File Reference
#include "auto/version.h"
#include "common.hpp"
#include <windows.h>
#include <irrlicht.h>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>
#include "rsa/RSA.h"
#include "sha1.hpp"
#include "protocol.hpp"
#include <boost/thread/thread.hpp>
#include <boost/filesystem.hpp>
#include <boost/variant.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/uuid/sha1.hpp>
#include "server.hpp"
#include "client.hpp"
#include "settings.hpp"
Classes
class ClientEventReceiver
Functions
void client_default_config (Configurator &cfg)
void testNotify (bvnet::session *s)
void loginDone (bvnet::session *s, bool *authOk, bool *doneFlag)
void onGetAccount (bvnet::session *s, u32 *acctOb, bool *doneFlag)
void testLogin (bvnet::session *s, KeyPair *ckey, bool *authOk, bool *doneFlag)
int main (int argc, char **argv)
Variables
volatile bool serverActive
volatile bool req_serverQuit
Function Documentation
void client_default_config (Configurator & cfg)
Definition at line 81 of file main.cpp.
Referenced by main().
void loginDone (bvnet::session * s, bool * authOk, bool * doneFlag)
Definition at line 111 of file main.cpp.
References bvnet::session::getarg().
Referenced by testLogin().
int main (int argc, char ** argv)
Definition at line 165 of file main.cpp.
References bvnet::session::argcount(), bvnet::session::argtype(), auto_ver, bvnet::session::bootstrap(), client_default_config(), bvnet::session::getarg(), bvnet::session::getRemote(), bvnet::session::hasRemote(), LOCK_COUT, onGetAccount(), bvnet::session::poll(), protocol_main_init(), Configurator::read_cmdline(), req_serverQuit, bvnet::session::run(), bvnet::session::send_call(), bvnet::session::send_string(), server_main(), serverActive, bvnet::session::set_conn(), testLogin(), testNotify(), UNLOCK_COUT, v2int, v2str, bvnet::vtBlob, bvnet::vtDeath, bvnet::vtDMC, bvnet::vtFloat, bvnet::vtInt, bvnet::vtMethod, bvnet::vtObref, and bvnet::vtString.
void onGetAccount (bvnet::session * s, u32 * acctOb, bool * doneFlag)
Definition at line 117 of file main.cpp.
References bvnet::session::getarg(), bvnet::obref::id, LOCK_COUT, and UNLOCK_COUT.
Referenced by main().
void testLogin (bvnet::session * s, KeyPair * ckey, bool * authOk, bool * doneFlag)
Definition at line 136 of file main.cpp.
References bvnet::session::getarg(), loginDone(), bvnet::session::send_call(), and bvnet::session::send_string().
Referenced by main().
void testNotify (bvnet::session * s)
Definition at line 104 of file main.cpp.
References bvnet::session::getarg(), LOCK_COUT, and UNLOCK_COUT.
Referenced by main().
Variable Documentation
volatile bool req_serverQuit
Definition at line 79 of file main.cpp.
Referenced by main(), server_boot(), and server_main().
volatile bool serverActive
Definition at line 73 of file main.cpp.
Referenced by main(), and server_main().