Blockiverse: server.cpp File Reference
server.cpp File Reference
#include "auto/version.h"
#include "common.hpp"
#include <windows.h>
#include <iostream>
#include <map>
#include "sqlite/sqlite3.h"
#include "protocol.hpp"
#include "server.hpp"
#include "settings.hpp"
#include "database.hpp"
#include <boost/thread.hpp>
#include <boost/filesystem.hpp>
Classes
struct context
class context_manager
Typedefs
typedef std::map
< boost::thread *, io_service * > s_list
Functions
void server_default_config (Configurator &cfg)
DWORD WINAPI server_boot (LPVOID lpvCtx)
DWORD WINAPI server_main (LPVOID argvoid)
Variables
boost::random::random_device entropy
s_list sessions
Class Documentation
struct context
Definition at line 38 of file server.cpp.
Class Members
object * root
session * session
socket * socket
Typedef Documentation
typedef std::map<boost::thread*,io_service*> s_list
Definition at line 87 of file server.cpp.
Function Documentation
DWORD WINAPI server_boot (LPVOID lpvCtx)
Definition at line 62 of file server.cpp.
References bvnet::session::bootstrap(), LOCK_COUT, req_serverQuit, context::root, bvnet::session::run(), context::session, context::socket, and UNLOCK_COUT.
Referenced by server_main().
void server_default_config (Configurator & cfg)
Definition at line 34 of file server.cpp.
Referenced by server_main().
DWORD WINAPI server_main (LPVOID argvoid)
Definition at line 90 of file server.cpp.
References auto_ver, bvdb::init_db(), LOCK_COUT, Configurator::read_cmdline(), req_serverQuit, context::root, bvdb::SQLiteDB::runOnce(), server_boot(), server_default_config(), serverActive, context::session, sessions, bvnet::session::set_conn(), context::socket, UNLOCK_COUT, and v2int.
Referenced by main().
Variable Documentation
boost::random::random_device entropy
Definition at line 32 of file server.cpp.
Referenced by serverRoot::dmc_LoginClient().
s_list sessions
Definition at line 88 of file server.cpp.
Referenced by server_main().