Blockiverse: server.hpp File Reference
server.hpp File Reference
#include "common.hpp"
#include <windows.h>
#include "protocol.hpp"
#include "database.hpp"
#include "sha1.hpp"
#include <boost/nondet_random.hpp>
#include "RSA/rsa.h"
Classes
class Account
class serverRoot
Typedefs
typedef SQLiteDB::statement statement
typedef SQLiteDB::query_result query_result
typedef bvnet::value_queue value_queue
Functions
DWORD WINAPI server_main (LPVOID argvoid)
Variables
volatile bool serverActive
volatile bool req_serverQuit
boost::random::random_device entropy
Typedef Documentation
typedef SQLiteDB::query_result query_result
Definition at line 39 of file server.hpp.
typedef SQLiteDB::statement statement
Definition at line 38 of file server.hpp.
typedef bvnet::value_queue value_queue
Definition at line 40 of file server.hpp.
Function Documentation
DWORD WINAPI server_main (LPVOID argvoid)
Definition at line 90 of file server.cpp.
References auto_ver, bvdb::init_db(), LOCK_COUT, Configurator::read_cmdline(), req_serverQuit, context::root, bvdb::SQLiteDB::runOnce(), server_boot(), server_default_config(), serverActive, context::session, sessions, bvnet::session::set_conn(), context::socket, UNLOCK_COUT, and v2int.
Referenced by main().
Variable Documentation
boost::random::random_device entropy
Definition at line 32 of file server.cpp.
Referenced by serverRoot::dmc_LoginClient().
volatile bool req_serverQuit
Definition at line 79 of file main.cpp.
Referenced by main(), server_boot(), and server_main().
volatile bool serverActive
Definition at line 73 of file main.cpp.
Referenced by main(), and server_main().