Blockiverse: bvdb::DBError Struct Reference
bvdb::DBError Struct Reference
Errors SQLite and database access errors Bad parameters, incorrect usage, violated constraints, etc.
#include <database.hpp>
Public Types
enum _flags { noop, release }
Public Member Functions
DBError (const char *msg, _flags f=noop)
Static Public Member Functions
static void busy_aware_throw (int code, const char *msg, _flags f=noop)
Detailed Description
Errors SQLite and database access errors Bad parameters, incorrect usage, violated constraints, etc.
Definition at line 48 of file database.hpp.
Member Enumeration Documentation
enum bvdb::DBError::_flags
Enumerator
noop
release
Definition at line 49 of file database.hpp.
Constructor & Destructor Documentation
bvdb::DBError::DBError (const char * msg, _flags f = noop) inline
Definition at line 57 of file database.hpp.
References release.
Referenced by busy_aware_throw().
Member Function Documentation
static void bvdb::DBError::busy_aware_throw (int code, const char * msg, _flags f = noop) inline static
Definition at line 50 of file database.hpp.
References DBError().
Referenced by bvdb::SQLiteDB::bind(), bvdb::SQLiteDB::bind_null(), bvdb::SQLiteDB::prepare(), bvdb::SQLiteDB::run(), bvdb::SQLiteDB::runOnce(), and bvdb::SQLiteDB::SQLiteDB().
The documentation for this struct was generated from the following file:
database.hpp